<?php

$page = array(
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?f[0]=bs_project_sandbox%3A1","multiple_results"=>true),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=1&f[0]=bs_project_sandbox%3A1","multiple_results"=>true),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=2&f[0]=bs_project_sandbox%3A1","multiple_results"=>true),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=3&f[0]=bs_project_sandbox%3A1","multiple_results"=>true),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=4&f[0]=bs_project_sandbox%3A1","multiple_results"=>true),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=5&f[0]=bs_project_sandbox%3A1","multiple_results"=>true),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=6&f[0]=bs_project_sandbox%3A1","multiple_results"=>true),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=7&f[0]=bs_project_sandbox%3A1","multiple_results"=>true),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=8&f[0]=bs_project_sandbox%3A1","multiple_results"=>true),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=9&f[0]=bs_project_sandbox%3A1","multiple_results"=>true),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=10&f[0]=bs_project_sandbox%3A1","multiple_results"=>true),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=11&f[0]=bs_project_sandbox%3A1","multiple_results"=>true),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=12&f[0]=bs_project_sandbox%3A1","multiple_results"=>true),
  array("type" => "Distribution","url" => "http://drupal.org/project/distributions/commerce?f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0","multiple_results"=>true),
  array("type" => "Theme","url" => "http://drupal.org/search/site/commerce?f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Atheme","multiple_results"=>true),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","multiple_results"=>true),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=1&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","multiple_results"=>true),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=2&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","multiple_results"=>true),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=3&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","multiple_results"=>true),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=4&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","multiple_results"=>true),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=5&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","multiple_results"=>true),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=6&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","multiple_results"=>true),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=7&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","multiple_results"=>true),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=8&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","multiple_results"=>true),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=9&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","multiple_results"=>true),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=10&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","multiple_results"=>true),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=11&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","multiple_results"=>true),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=12&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","multiple_results"=>true),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=13&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","multiple_results"=>true),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=14&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","multiple_results"=>true),
  array("type" => "Module","url" => "http://drupal.org/project/inline_entity_form","multiple_results"=>false),
  array("type" => "Module","url" => "http://drupal.org/project/addressfield","multiple_results"=>false),
  array("type" => "Module","url" => "http://drupal.org/project/physical","multiple_results"=>false),
  array("type" => "Module","url" => "http://drupal.org/project/views","multiple_results"=>false),
  array("type" => "Module","url" => "http://drupal.org/project/rules","multiple_results"=>false),
  array("type" => "Module","url" => "http://drupal.org/project/entity","multiple_results"=>false),
  array("type" => "Module","url" => "http://drupal.org/project/tree","multiple_results"=>false),
  array("type" => "Module","url" => "http://drupal.org/project/facetapi","multiple_results"=>false),
  array("type" => "Module","url" => "http://drupal.org/project/search_api","multiple_results"=>false),
  array("type" => "Module","url" => "http://drupal.org/project/editablefields","multiple_results"=>false),
  array("type" => "Module","url" => "http://drupal.org/project/jirafe","multiple_results"=>false),
  array("type" => "Module","url" => "http://drupal.org/project/yottaa","multiple_results"=>false),
  array("type" => "Module","url" => "http://drupal.org/project/dc_cart_ajax","multiple_results"=>false),
  array("type" => "Module","url" => "http://drupal.org/project/commerce_product_clone","multiple_results"=>false),
  array("type" => "Module","url" => "http://drupal.org/project/product_reference_view","multiple_results"=>false),
  array("type" => "Module","url" => "http://drupal.org/project/dc_co_pages","multiple_results"=>false),
  array("type" => "Sandbox","url" => "http://drupal.org/sandbox/webmasterkai/1305710","multiple_results"=>false),
  array("type" => "Sandbox","url" => "http://drupal.org/sandbox/webmasterkai/1313714","multiple_results"=>false),
  array("type" => "Theme","url" => "http://drupal.org/project/corporateclean","multiple_results"=>false),
  array("type" => "Theme","url" => "http://drupal.org/project/bluemasters","multiple_results"=>false),
  array("type" => "Theme","url" => "http://drupal.org/project/sky","multiple_results"=>false),
  array("type" => "Theme","url" => "http://drupal.org/project/business","multiple_results"=>false),
  array("type" => "Theme","url" => "http://drupal.org/project/andromeda","multiple_results"=>false),
  array("type" => "Theme","url" => "http://drupal.org/project/touch","multiple_results"=>false),
  array("type" => "Theme","url" => "http://drupal.org/project/busy","multiple_results"=>false),
  array("type" => "Theme","url" => "http://drupal.org/project/jackson","multiple_results"=>false),
  array("type" => "Module","url" => "http://drupal.org/project/goals","multiple_results"=>false),
  array("type" => "Module","url" => "http://drupal.org/project/rules_linkevent","multiple_results"=>false),
  array("type" => "Module","url" => "http://drupal.org/project/customer_profile_type_ui","multiple_results"=>false)
);

foreach ($page as $source) {
  $db->query("INSERT primary_sources (tid, url, multi) 
VALUES ('".$source["type"]."', '".$source["url"]."','".$source["multiple_results"]."')");
}