<?php

$page = array(
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?f[0]=bs_project_sandbox%3A1","source_type"=>"Search Result"),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=1&f[0]=bs_project_sandbox%3A1","source_type"=>"Search Result"),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=2&f[0]=bs_project_sandbox%3A1","source_type"=>"Search Result"),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=3&f[0]=bs_project_sandbox%3A1","source_type"=>"Search Result"),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=4&f[0]=bs_project_sandbox%3A1","source_type"=>"Search Result"),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=5&f[0]=bs_project_sandbox%3A1","source_type"=>"Search Result"),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=6&f[0]=bs_project_sandbox%3A1","source_type"=>"Search Result"),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=7&f[0]=bs_project_sandbox%3A1","source_type"=>"Search Result"),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=8&f[0]=bs_project_sandbox%3A1","source_type"=>"Search Result"),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=9&f[0]=bs_project_sandbox%3A1","source_type"=>"Search Result"),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=10&f[0]=bs_project_sandbox%3A1","source_type"=>"Search Result"),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=11&f[0]=bs_project_sandbox%3A1","source_type"=>"Search Result"),
  array("type" => "Sandbox","url" => "http://drupal.org/project/modules/commerce%20-ubercart%20-%22e-commerce%22%20-deprecated%20-uc%20-Ubercart%20-%22Commerce%20Sandbox%22%20-deleted%20-eCommerce?page=12&f[0]=bs_project_sandbox%3A1","source_type"=>"Search Result"),
  array("type" => "Distribution","url" => "http://drupal.org/project/distributions/commerce?f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0","source_type"=>"Search Result"),
  array("type" => "Theme","url" => "http://drupal.org/search/site/commerce?f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Atheme","source_type"=>"Search Result"),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","source_type"=>"Search Result"),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=1&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","source_type"=>"Search Result"),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=2&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","source_type"=>"Search Result"),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=3&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","source_type"=>"Search Result"),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=4&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","source_type"=>"Search Result"),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=5&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","source_type"=>"Search Result"),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=6&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","source_type"=>"Search Result"),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=7&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","source_type"=>"Search Result"),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=8&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","source_type"=>"Search Result"),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=9&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","source_type"=>"Search Result"),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=10&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","source_type"=>"Search Result"),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=11&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","source_type"=>"Search Result"),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=12&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","source_type"=>"Search Result"),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=13&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","source_type"=>"Search Result"),
  array("type" => "Module","url" => "http://drupal.org/search/site/commerce?page=14&f[0]=drupal_core%3A103&f[1]=bs_project_sandbox%3A0&f[2]=ss_meta_type%3Amodule","source_type"=>"Search Result"),
  array("type" => "Module","url" => "http://drupal.org/project/inline_entity_form","source_type"=>"Module Page"),
  array("type" => "Module","url" => "http://drupal.org/project/addressfield","source_type"=>"Module Page"),
  array("type" => "Module","url" => "http://drupal.org/project/physical","source_type"=>"Module Page"),
  array("type" => "Module","url" => "http://drupal.org/project/views","source_type"=>"Module Page"),
  array("type" => "Module","url" => "http://drupal.org/project/rules","source_type"=>"Module Page"),
  array("type" => "Module","url" => "http://drupal.org/project/entity","source_type"=>"Module Page"),
  array("type" => "Module","url" => "http://drupal.org/project/tree","source_type"=>"Module Page"),
  array("type" => "Module","url" => "http://drupal.org/project/facetapi","source_type"=>"Module Page"),
  array("type" => "Module","url" => "http://drupal.org/project/search_api","source_type"=>"Module Page"),
  array("type" => "Module","url" => "http://drupal.org/project/editablefields","source_type"=>"Module Page"),
  array("type" => "Module","url" => "http://drupal.org/project/jirafe","source_type"=>"Module Page"),
  array("type" => "Module","url" => "http://drupal.org/project/yottaa","source_type"=>"Module Page"),
  array("type" => "Module","url" => "http://drupal.org/project/dc_cart_ajax","source_type"=>"Module Page"),
  array("type" => "Module","url" => "http://drupal.org/project/commerce_product_clone","source_type"=>"Module Page"),
  array("type" => "Module","url" => "http://drupal.org/project/product_reference_view","source_type"=>"Module Page"),
  array("type" => "Module","url" => "http://drupal.org/project/dc_co_pages","source_type"=>"Module Page"),
  array("type" => "Sandbox","url" => "http://drupal.org/sandbox/webmasterkai/1305710","source_type"=>"Module Page"),
  array("type" => "Sandbox","url" => "http://drupal.org/sandbox/webmasterkai/1313714","source_type"=>"Module Page"),
  array("type" => "Theme","url" => "http://drupal.org/project/corporateclean","source_type"=>"Module Page"),
  array("type" => "Theme","url" => "http://drupal.org/project/bluemasters","source_type"=>"Module Page"),
  array("type" => "Theme","url" => "http://drupal.org/project/sky","source_type"=>"Module Page"),
  array("type" => "Theme","url" => "http://drupal.org/project/business","source_type"=>"Module Page"),
  array("type" => "Theme","url" => "http://drupal.org/project/andromeda","source_type"=>"Module Page"),
  array("type" => "Theme","url" => "http://drupal.org/project/touch","source_type"=>"Module Page"),
  array("type" => "Theme","url" => "http://drupal.org/project/busy","source_type"=>"Module Page"),
  array("type" => "Theme","url" => "http://drupal.org/project/jackson","source_type"=>"Module Page"),
  array("type" => "Module","url" => "http://drupal.org/project/goals","source_type"=>"Module Page"),
  array("type" => "Module","url" => "http://drupal.org/project/rules_linkevent","source_type"=>"Module Page"),
  array("type" => "Module","url" => "http://drupal.org/project/customer_profile_type_ui","source_type"=>"Module Page")
);

foreach ($page as $source) {
  $db->query("INSERT primary_sources (etid, url, stid) 
VALUES ('".$source["type"]."', '".$source["url"]."','".$source["source_type"]."')");
}